name: planificador_frontend
description: "Una aplicación de planificación para docentes."
# La siguiente línea previene la publicación accidental en pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# DEPENDENCIAS:
# Aquí se listan los paquetes externos que tu aplicación necesita para funcionar.
dependencies:
  flutter:
    sdk: flutter

  # El paquete de iconos de estilo iOS.
  cupertino_icons: ^1.0.2

  # Paquete para hacer peticiones HTTP a un servidor/backend.
  http: ^1.2.1

  # Paquete para guardar datos sencillos en la memoria local del dispositivo.
  shared_preferences: ^2.2.3

  intl: ^0.19.0 # <--- AÑADE ESTA LÍNEA

# DEPENDENCIAS DE DESARROLLO:
# Paquetes que solo se necesitan para desarrollar y probar la app,
# no se incluyen en la versión final que se instala en el teléfono.
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Herramientas para ayudar a escribir un código más limpio y estándar.
  flutter_lints: ^3.0.0

# CONFIGURACIÓN DE FLUTTER:
# Esta sección contiene configuraciones específicas para el framework de Flutter.
flutter:

  # La siguiente línea asegura que se pueda usar la iconografía de Material Design.
  uses-material-design: true

  # Para añadir recursos como imágenes a tu aplicación, descomenta esta sección:
  # assets:
  #   - assets/images/logo.png
  #   - assets/images/profile_background.jpg

  # Para añadir fuentes personalizadas, descomenta esta sección:
  # fonts:
  #   - family: SplineSans
  #     fonts:
  #       - asset: assets/fonts/SplineSans-Regular.ttf
  #       - asset: assets/fonts/SplineSans-Bold.ttf
  #         weight: 700