# === INICIO MODIFICACIÓN: Se corrige el formato de los comentarios y se ajusta la estructura. ===
name: planificador_frontend
description: "Una aplicación de planificación para docentes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  table_calendar: ^3.1.1
  intl: ^0.20.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
# === FIN MODIFICACIÓN ===