// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHZ2s4xWCraSEgC7PU1dNQZ7P_bf0vVNo',
    appId: '1:23073331643:web:0cd2bc23ab61a609200c9e',
    messagingSenderId: '23073331643',
    projectId: 'planificador-docente-a32f9',
    authDomain: 'planificador-docente-a32f9.firebaseapp.com',
    storageBucket: 'planificador-docente-a32f9.firebasestorage.app',
    measurementId: 'G-ZDX0PT5TRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJYDue850nNyOue7B1CfsTdTSppbM93wQ',
    appId: '1:23073331643:android:cb3e0d536b2628cb200c9e',
    messagingSenderId: '23073331643',
    projectId: 'planificador-docente-a32f9',
    storageBucket: 'planificador-docente-a32f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDoapaA8_yGNjWf56i9UXSuiCnT1tgD0I',
    appId: '1:23073331643:ios:46d1d1436d5abe7f200c9e',
    messagingSenderId: '23073331643',
    projectId: 'planificador-docente-a32f9',
    storageBucket: 'planificador-docente-a32f9.firebasestorage.app',
    iosBundleId: 'com.example.planificadorFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDoapaA8_yGNjWf56i9UXSuiCnT1tgD0I',
    appId: '1:23073331643:ios:46d1d1436d5abe7f200c9e',
    messagingSenderId: '23073331643',
    projectId: 'planificador-docente-a32f9',
    storageBucket: 'planificador-docente-a32f9.firebasestorage.app',
    iosBundleId: 'com.example.planificadorFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHZ2s4xWCraSEgC7PU1dNQZ7P_bf0vVNo',
    appId: '1:23073331643:web:5bf8a38c7004d2a3200c9e',
    messagingSenderId: '23073331643',
    projectId: 'planificador-docente-a32f9',
    authDomain: 'planificador-docente-a32f9.firebaseapp.com',
    storageBucket: 'planificador-docente-a32f9.firebasestorage.app',
    measurementId: 'G-JCVL4GG69J',
  );

}